# Generated by Django 2.1.5 on 2019-06-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_roomtype_shortnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'MESSAGE',
                'verbose_name_plural': 'MESSAGES',
            },
        ),
        migrations.AlterModelOptions(
            name='adminaddress',
            options={'verbose_name': 'ADMIN INFO', 'verbose_name_plural': 'ADMIN INFO'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'ROOM INFO', 'verbose_name_plural': 'ROOM INFO'},
        ),
    ]
