# Generated by Django 2.1.5 on 2019-06-24 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_auto_20190624_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
