# Generated by Django 2.1.5 on 2019-06-24 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_messagedata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedata',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
